### ISSUE TITLE
It is so difficult to install the solftware

### ISSUE THREAD

**Issue by bioinformaticspcj** [phyloacc/PhyloAcc#10]
Dear the author:

I am a student working in Chinese Academy of Sciences. It is my pleasure to have a chance to use this valuable software to open a door for me about the CCNEs. But, when I try to install it, I meet many bugs. In the PhyloAcc directory, excutable file "PhyloAcc" is made by Armadillo version 7, not armadillo version 8 as you said. So, it can not be excuted. Additionally, if you want to install it, you should modify the "Makefile" file to change the "gsl lib" path. All in all, in my opinion, the software may be improved for a easier way to install.

Thanks a lot for your important software, looking forword to hear from you soon.
Best wishes,
bioinformatic_pcj

**Comment by xyz111131** [comment]
Thanks for your suggestions. Have you installed the software successfully? I'll improve the installation procedure during the summer.

**Comment by fandw06** [comment]
> Dear the author:
> 
> I am a student working in Chinese Academy of Sciences. It is my pleasure to have a chance to use this valuable software to open a door for me about the CCNEs. But, when I try to install it, I meet many bugs. In the PhyloAcc directory, excutable file "PhyloAcc" is made by Armadillo version 7, not armadillo version 8 as you said. So, it can not be excuted. Additionally, if you want to install it, you should modify the "Makefile" file to change the "gsl lib" path. All in all, in my opinion, the software may be improved for a easier way to install.
> 
> Thanks a lot for your important software, looking forword to hear from you soon.
> Best wishes,
> bioinformatic_pcj

Hey bioinformatic_pcj, thanks for your feedback! Which OS do you use? It might be helpful to provide more environment info.

**Comment by bioinformaticspcj** [comment]
You are welcome, yes, I have installed it successfully on Centos 7 with gcc 7.3. Thanks for the plan to improve it.




------------------ 原始邮件 ------------------
发件人: "xyz111131"<notifications@github.com>;
发送时间: 2019年6月12日(星期三) 凌晨1:59
收件人: "xyz111131/PhyloAcc"<PhyloAcc@noreply.github.com>;
抄送: "Monkeyjun"<2532090267@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xyz111131/PhyloAcc] It is so difficult to install the solftware(#10)




Thanks for your suggestions. Have you installed the software successfully? I'll improve the installation procedure during the summer.

**Comment by gwct** [comment]
Hopefully this is even easier now that we have packaged the software for conda. If conda is already installed, you should be able to create an environment and simply type:

```bash
conda install phyloacc
```

to install the software. For more information see the [Install page on the website](https://phyloacc.github.io/install.html).
