### ISSUE TITLE
Not detecting elements

### ISSUE THREAD

**Issue by luisacusick** [phyloacc/PhyloAcc#12]
Hi, when I try to run this program it terminates without generating any output. I think it might be related to not detecting any elements. My .bed file is formatted like your sample. Here's the output:
```
# total length = 32652966 (0). # Species = 63. # elements = 0. Mean gene set size = 0.0000.
# Burn-ins = 500. # MCMC Updates = 1000. # adaptive frequency = 500.  RND SEED = 5.
# Threads = 1

The species in profile and tree match perfectly. Reorder the species in profile matrix by the tree.

InitPhyloTree finished
0 of elements to be computed
Running MCMC chain 1 ...


time used:  0 min.
```

Have you seen this error before? 

Thank you!

**Comment by xyz111131** [comment]
That’s strange. It seems the program didn’t read the bed file. Could you please check if the bed file has “\t” (tab) as the delimiter? Or you could send me a few lines of the bed file.

**Comment by luisacusick** [comment]
That solved the problem. Thank you very much!
