### ISSUE TITLE
Sample Tg root error

### ISSUE THREAD

**Issue by luisacusick** [phyloacc/PhyloAcc#13]
Hi, 

The output table is filled with 0s, and each element prints a statement that looks like this:

Standard exception: Sample Tg root error
0

What is a Sample Tg root error?

Thank you!

**Comment by xyz111131** [comment]
Hi,

The algorithm needs to sample the ancestral sequences including the root to infer the substitution rate. It might be because the probability of each base pair is too small at root. How long is your element? Are there many indels in your sequences? What is the character for the indel?

**Comment by luisacusick** [comment]
The elements are of varying lengths, but the whole alignment is 32652966 bases long. There are not many indels in the sequences, and there is not an indel character in the alignment.

**Comment by xyz111131** [comment]
The total length is fine since the alignment was already successfully loaded into memory. Do all the elements have this error or only some long elements? I’m sorry I don’t know what the problem is. But if you could send me a few elements and the tree (you can put some random names to the species), I could try to debug for you.

**Comment by luisacusick** [comment]
All of the elements have this issue. I think it might be caused by incorrectly labelled internal nodes in the tree, so I will try to fix that. Thank you though!

**Comment by luisacusick** [comment]
Can you help me troubleshoot? I am still having trouble with the program. 
I attached relevant files; The sample_alignment is the second element in the bed file (MTRNR2L1). I took it out of the full alignment so that I wouldn't have to send a very large file. Let me know if I should send you any other information. Thank you very [much!]

[Sample Input.zip](https://github.com/xyz111131/PhyloAcc/files/3655099/Sample.Input.zip)

**Comment by xyz111131** [comment]
Hi,

The species name in the fasta file has to be the same as in the mod file. In your fasta file, the name is 
like "#15# <unknown description>”, so the program cannot recognize.

**Comment by xyz111131** [comment]
Also, there should be no space between the species name and semicolon in the parameter file:

e.g. "bosTau7; calJac3;” -> "bosTau7;calJac3;"

**Comment by luisacusick** [comment]
I made these fixes and am still getting a sample tg root error. The output screen says that everything is successfully read in, but the output table is all zeros. 

Here's what the output looks like: 

Loading input data and running parameters......
Loading program configurations from paParamFile.txt......
Loading phylogenetic tree from /zfs1/nclark/Luisa/PhyloAccInput/mamTrees.mod......
 

> total length = 32652966 (19149). # Species = 63. # elements = 19149. Mean gene set size = 1706.2048.
> Burn-ins = 500. # MCMC Updates = 1000. # adaptive frequency = 500.  RND SEED = 5.
> Threads = 1
> 
> The species in profile and tree match perfectly. Reorder the species in profile matrix by the tree.
> 
> InitPhyloTree finished
> 19149 of elements to be computed
> Running MCMC chain 1 ...
> Init lambda
> root: 124
> 
> 0: -inf, -inf, 1.0000, 0.5000, 1.2000, 0.0001, 0.5000, 0.3000, 0.0000
> 124: 0,
> 0
> 0 Standard exception: Sample Tg root error
> Init lambda
> root: 124

(The output for every element after element 0 is the same as for element 0)

I attached my input, with a truncated version of the fasta file. Thank you!


[PhyloAccSample.zip](https://github.com/xyz111131/PhyloAcc/files/3763870/PhyloAccSample.zip)

**Comment by xyz111131** [comment]
Hi, 

Have you figured out? If not, I’ll look into it tomorrow.

Best,

**Comment by luisacusick** [comment]
Sorry about that. Here's the correct file. 

Thank you!
[fas.zip](https://github.com/xyz111131/PhyloAcc/files/3784329/fas.zip)

**Comment by xyz111131** [comment]
I didn't find hg19 in your alignment file, but has hg19 in the tree file.

**Comment by luisacusick** [comment]
My mistake, sorry. Here is the correctly subset fasta file. The alignment I am using does contain hg19. 
[subset_aln_2.zip](https://github.com/xyz111131/PhyloAcc/files/3795811/subset_aln_2.zip)

**Comment by xyz111131** [comment]
It's because of a branch has near zero length. Just updated the codes in SRC/ to solve this issue. You could try download and compile the new code. But I would suggest to subset the sequence.  It's much longer than CNEE that the program was used and it seems that the sequence is protein coding sequence whose codon structure is not captured by PhyloAcc.
