### ISSUE TITLE
PhyloAcc: symbol lookup error: PhyloAcc: undefined symbol: __libm_feature_flag

### ISSUE THREAD

**Issue by Wei-Gordon** [phyloacc/PhyloAcc#14]
[error.txt](https://github.com/xyz111131/PhyloAcc/files/3484131/error.txt)
[versions.txt](https://github.com/xyz111131/PhyloAcc/files/3484136/versions.txt)
[ldpath.txt](https://github.com/xyz111131/PhyloAcc/files/3484133/ldpath.txt)

can't properly install PhyloAcc. I created a Conda environment and attached the environment file here. ldpath.txt is my LD_LIBRARY_PATH
could not Conda install armadillo version 7 so installed manually: armadillo-7.800.2
would super appreciate if you can help me figure out why I can't install PhyloAcc properly!

**Comment by JJZhao123** [comment]
I have the same issue with installing it without root permission. 
It gives the error :

PhyloAcc: symbol lookup error: PhyloAcc: undefined symbol: __libm_feature_flag

**Comment by funqc** [comment]
Maybe you need to modify the LIB parameters in the makefile
```
GSL_INCLUDE=/usr/local/include/
GSL_LIB=/usr/local/lib/
```

**Comment by Wei-Gordon** [comment]
parameters were modified in makefile but same error ensues
[makefile.txt](https://github.com/xyz111131/PhyloAcc/files/3497804/makefile.txt)

**Comment by xyz111131** [comment]
I didn't use Conda environment to install the package. Armadillo could be installed by "brew install homebrew/science/armadillo".

**Comment by xyz111131** [comment]
You could try "echo ${GSL_HOME}" to see where GSL is located.

**Comment by Wei-Gordon** [comment]
Thank you, I figured it out. I created a soft link for armadillo lib

This is what I did:
cd $GSL_LIB 
ln -s libarmadillo.so.7 libarmadillo.so

**Comment by yuzhenpeng** [comment]
Dear Wei, 
I met the same problem with you. And I try `ln -s libarmadillo.so.7 libarmadillo.so`. But it also give warnings: PhyloAcc: symbol lookup error: PhyloAcc: undefined symbol: __libm_feature_flag.

Could you give me some help. @xyz111131 @Wei-Gordon 

Zhenpeng.

**Comment by Wei-Gordon** [comment]
hi @yuzhenpeng did you check the README for my full instructions on installing PhyloAcc in a conda environment? please let me know if that works for you. Above in this thread I posted all my conda versions in verstions.txt (i used gcc 7.3.0)

**Comment by yuzhenpeng** [comment]
[my_computer_version.txt](https://github.com/xyz111131/PhyloAcc/files/4723358/my_computer_version.txt)
Yeah, but I don't know why. Thank you.

**Comment by gwct** [comment]
PhyloAcc is now fully installable as a conda package from bioconda. If conda is already installed, you should be able to create an environment and simply type:

```bash
conda install phyloacc
```

to install the software. For more information see the [Install page on the website](https://phyloacc.github.io/install.html).
