### ISSUE TITLE
Can multiple simultaneous PhyloAcc jobs add to the same rate file?

### ISSUE THREAD

**Issue by luisacusick** [phyloacc/PhyloAcc#18]
Hi,

I am running PhyloAcc on a set of ~20k genes for 63 species on a cluster that uses slurm to schedule jobs. I submitted a slurm script that created 25 simultaneous jobs, with each one running PhyloAcc on 800 genes. The rate files (ex. <name>_rate_postZ_M0.txt) have the correct row and column names but is otherwise empty, even though the job is done. Do I need to run this so that each job edits a different output file and then concatenate them when all are completed? Thank you!

**Comment by tsackton** [comment]
Yes, I believe you need to run it so that each job edits a different output file.
