### ISSUE TITLE
How to get the fasta file from phastcon cnee bed.

### ISSUE THREAD

**Issue by Ran-tian** [phyloacc/PhyloAcc#19]
Dear author,
I follow the pipeline in your paper to run the PhyloAcc. I already identified the cnee using phascon, but I don't know how to obtain the fasta of cnee (based on the maf and bed?) and produce a new bed (for concatenated cnee of each species). Guess the PhyloAcc only takes the fasta file as input. Hope get your help.
Looking forward to your reply.
Thanks.

**Comment by yuzhenpeng** [comment]
Hi Zhirui,
I also want to know how to prepare the CNE fasta file and corresponding bed file as mentioned above by Ran.

Thank you.  @xyz111131

**Comment by xyz111131** [comment]
Yes, PhyloAcc can only take fasta as input now. I used ~/software/phast-master/bin/msa_split *.maf --features *.bed --by-category --out-format FASTA --out-root * to convert maf to fasta.

**Comment by xyz111131** [comment]
and msa_view --in-format MAF *.maf  >*.fa to convert the whole alignment.

**Comment by xyz111131** [comment]
Probably add --refseq and --do-cats 1 to the arguments of msa_split. Yes I generated a new bed by some simple scripts.

**Comment by yuzhenpeng** [comment]
Hi Zhirui,
Thank for your positive response. I seem to understand something. I'm a novice bioinformatics, not very good at programming. Would you mind sharing these scripts?
