### ISSUE TITLE
What is the branch length and color plotted by plotZPost?

### ISSUE THREAD

**Issue by binlu1981** [phyloacc/PhyloAcc#25]
Hi @xyz111131 ,

I looked the R script and found the code
`mytree$edge.length <-  mytree$edge.length*(posterior_z[1,] + posterior_z[2,] * ratio1 + posterior_z[3,]* ratio2)`
Why posterior probability * n_rate or c_rate here? Also what the color mean?  Dose it represents posterior probability 3?
And should I selected candidates that have higher posterior_3 and logBF1 ? 

Best regards
Bin

**Comment by xyz111131** [comment]
Hi Bin, 

the edge length represents expected substitution rate, the right hand side is like a conditional expectation formula. The color means the posterior mean of Z. If the posterior probability 3 is higher, then it will be more red. Yes you could select candidates with higher posterior_3 and logBF1, and you might also add logBF2>0. 

Best,

**Comment by binlu1981** [comment]
Got it! Thanks for quick replay.

**Comment by binlu1981** [comment]
Hi @xyz111131 ,

One more question. Should I set significant threshold of posterior probability to 0.95?

**Comment by xyz111131** [comment]
Posterior probability > 0.95 should be fine.
