### ISSUE TITLE
How to select convergent CNEs

### ISSUE THREAD

**Issue by zzzchang** [phyloacc/PhyloAcc#28]
Dear author,

I have used PhyloAcc to calculate CNEs, I would like to ask how to filter the values of logBF1 and logBF2 based on the results obtained?
If I want to filter the convergent evolution of multiple species, what should I do?
Another question,how to count how many target species have evolved in each CNE?

Best regards
Chang Zhang

**Comment by xyz111131** [comment]
Is it resolved?

**Comment by zzzchang** [comment]
Dear author,

Thanks for quick replay. I still have a question about how to select convergent CNEs, If I set the target species’ posterior probability cutoff of >= 0.90 to define acceleration, Are there any requirements for the posterior probabilities of the control species? And are there any other parameters that need to be set?

Best regards
Chang Zhang

**Comment by xyz111131** [comment]
Dear Chang,

Thanks for the question. You might also set the cutoff for control species e.g. <= 0.1. Also, you could select the elements based on logBFs. If you want, you might adjust the CONSTOMIS parameter which controls to how likely missing species to be treated as accelerated. 

Best,
zhirui
