### ISSUE TITLE
 Is there any difference between PhyloAcc-GT and PhyloAcc-ST?

### ISSUE THREAD

**Issue by dx-lzu** [phyloacc/PhyloAcc#34]
Dear authors:
Could you tell the difference between PhyloAcc-GT and PhyloAc-ST? thanks~

Best regards
Xin Du

**Comment by xyz111131** [comment]
PhyloAcc-GT accounts for gene tree variation for each element; while PhyloAcc-ST assume that gene tree is the same as species tree. PhyloAcc-ST runs much faster than PhyloAcc-GT.
