### ISSUE TITLE
Standard exception: basic_string::substr: __pos when running without an ID file

### ISSUE THREAD

**Issue by gwct** [phyloacc/PhyloAcc#41]
A behavior I have noticed is that, even when running every element in the input bed file, the program sometimes crashes if it is not provided with an ID file specifying every element. Instead, exceptions along the lines of:

```
5484 Standard exception: basic_string::substr: __pos (which is 1616173) > this->size() (which is 1341856)
5485 Standard exception: basic_string::substr: __pos (which is 1616278) > this->size() (which is 1341856)
5486 Standard exception: basic_string::substr: __pos (which is 1616428) > this->size() (which is 1341856)
```

are reported.

If no ID file is given, we should just run on all elements in the bed file, so we need to track down what causes this. Until then, users should always provide an ID file when running PhyloAcc.

**Comment by xzk-fd** [comment]
Dear Gregg
I have met the same problem.
After I add the ID file that you sent me, it appears to be working well.
![image](https://user-images.githubusercontent.com/101171204/203212444-7b627e60-5879-483d-a02a-19446ae7c1f8.png)

After some time, it stops.
(Segmentation fault (core dumped))
![image](https://user-images.githubusercontent.com/101171204/203212130-49eae6f6-f819-4ca5-ae00-5dd9999911bb.png)

**Comment by gwct** [comment]
Hi again,
Can you tell me about how long it runs before you get the Segmentation fault? Thanks.

**Comment by xzk-fd** [comment]
hi，
It takes about 54 minutes.

**Comment by xzk-fd** [comment]
hi，
It takes about 54 minutes.

**Comment by gwct** [comment]
Yes, actually I see the same thing happening. @xyz111131 or @HanY-H, do you think you could take a look at this?

**Comment by xzk-fd** [comment]
I can't find something about my problem, can you give me a link?

Do you want me to look at this one  https://github.com/harvardinformatics/PhyloAcc-interface/issues/1, but I still don't know how to deal with the problem. 
Thank you for your any suggestions.

**Comment by gwct** [comment]
Hey again,
No this is the right place for your issue for now. I was able to replicate the problem, but I don't currently have a solution. I tagged a couple of the other developers to take a look, so hopefully they can help out also. I'll take another look today though and we'll keep you updated!

**Comment by xyz111131** [comment]
Segmentation Fault can be caused by many different reasons. Please provide your input files for better diagnostics.

**Comment by gwct** [comment]
Hopefully I'm not speaking too soon, but I think I found the problem: the bed file you sent me is in a 1-based coordinate system rather than the 0-based expected for bed files (https://en.wikipedia.org/wiki/BED_(file_format)#Coordinate_system). Since I have corrected this, it has been running for almost 3 hours while before I got the `Segmentation fault` after 2 hours.

To fix this, just subtract 1 from the start coordinate (column 2) of each element in the bed file. I did this with:

```bash
awk '{print $1"\t"$2-1"\t"$3}' input.bed > input0.bed
```

I'll let you know if this ends up erroring out again, but this might be the cause of the problem.

**Comment by gwct** [comment]
Just to update, the program has been running without `Segmentation fault` now for about 8 hours! I'm going to take that as a good sign and go ahead and cancel my run, but please let me know if the solution in the previous post works for you.

**Comment by xzk-fd** [comment]
oh, thank you for your help @gwct, let me have a try.

**Comment by xzk-fd** [comment]
> Hopefully I'm not speaking too soon, but I think I found the problem: the bed file you sent me is in a 1-based coordinate system rather than the 0-based expected for bed files (https://en.wikipedia.org/wiki/BED_(file_format)#Coordinate_system). Since I have corrected this, it has been running for almost 3 hours. Using the uncorrected bed file I got the `Segmentation fault` after 2 hours.
> 
> To fix this, just subtract 1 from the start coordinate (column 2) of each element in the bed file. I did this with:
> 
> ```shell
> awk '{print $1"\t"$2-1"\t"$3}' input.bed > input0.bed
> ```
> 
> I'll let you know if this ends up erroring out again, but this might be the cause of the problem.

yes, it works well !
Thank you very much for giving me so much help all the time!

**Comment by gwct** [comment]
I think this issue was fixed some time ago.
