### ISSUE TITLE
Trees for individual CNEs

### ISSUE THREAD

**Issue by gaurav-agavekar** [phyloacc/PhyloAcc#55]
Hi, 

I'm running PhyloAcc on a set of CNEs from ant genomes. The pipeline has been rather easy to execute, so thanks for the great interface and a user-friendly README. 

I had one question: how/where do I get trees for individual accelerated CNEs? As far as I can tell PhyloAcc doesn't generate/store these in the results. Do you have any recommendations for how to generate them? I would like to visualize the accelerations.

Also a quick note that PhyloAcc doesn't warn/auto-correct if ancestral nodes are not named with tree_doctor, it just fails (but works fine when the .mod file is first processed with tree_doctor). 

thanks,
Gaurav

**Comment by gwct** [comment]
Hi Gaurav,
Thanks! I'm glad you've found it easy to use!

If you just want to generate gene trees for particular elements, I would recommend [IQ-Tree](http://www.iqtree.org/) and then visualizing them in R with something like [ggtree](https://bioconductor.org/packages/release/bioc/html/ggtree.html).

If you're asking specifically about gene trees generated by PhyloAcc, , I'm not sure the gene trees were ever meant to be part of the official output for PhyloAcc, and they've never been tested for accuracy. I'm also not exactly sure how the branch lengths for these trees are calculated. Maybe @xyz111131 or @HanY-H could weigh in?

But they are available in a very complicated way in the **elem_Z** files for each batch, which are unfortunately not that easy to access. Basically, for each locus, you look up which _model_ (M0, M1, or M2) has the best marginal likelihood. Then in your phyloacc directory (the one you specified when using `phyloacc.py`), you would go to the path: `phyloacc-job-files/phyloacc-output/[batch]-phyloacc-[gt/st]-out/[batch]_[model]_elem_Z.txt`. Then, you'll have to look for the line with the ID for that locus from the current batch (NOT the overall id), and the gene tree will be the last column of that row.

And thanks for reporting this behavior about the un-labeled trees. I think we're aware of this and I'm working on several bug fixes that will get released soon. I'll tag this issue when we fix that one.

**Comment by gwct** [comment]
Checks for node labels in the trees have been added in [v2.3.1](https://github.com/phyloacc/PhyloAcc/tree/v2.3.1).

**Comment by gaurav-agavekar** [comment]
@gwct sorry, this fell through the cracks. I was referring to the example individual CNE trees shown in the Sackton et al. 2019 paper with accelerated clades in red. I found a way to visualize those, so I forgot to reply here, but thanks anyway for your help.

**Comment by kuangzhuoran** [comment]
Hi, May I ask how you addressed this issue?
If certain species have indeed undergone convergent acceleration in evolutionary rates at specific CNEs, I would think that directly building phylogenetic trees using tools like IQ-TREE should also be able to reproduce the results reported in Sackton et al. (2019).

**Comment by gwct** [comment]
@kuangzhuoran does my answer in #90 cover this for you? This issue was about how to access the gene trees from PhyloAcc.
