### ISSUE TITLE
phyloacc version

### ISSUE THREAD

**Issue by brantfaircloth** [phyloacc/PhyloAcc#71]
Following up on my post in #70 (re: checking v2.3.3 versus v2.3.1), it looks like the current version of phyloacc in bioconda:
```
bioconda/linux-64::phyloacc-2.3.3-py312h1869a9d_1
```
Is not reporting its version number correctly.  E.g. after installing,
```
$ phyloacc.py -v

# PhyloAcc version 2.3.1 released on March 26, 2024
```
However, I think this is actually v2.3.3.  It seems that the information in [info.yaml](https://github.com/phyloacc/PhyloAcc/blob/7bb2dfc2d839d81522dc0585753b2ef0fba8fd14/src/PhyloAcc-interface/phyloacc_lib/info.yaml#L1) has not been updated.

**Comment by gwct** [comment]
Oops! Should be an easy fix when I get back to work, though. I'll update here when fixed.

**Comment by gwct** [comment]
Should be fixed in the latest versions as long as I keep remembering to update it...
