### ISSUE TITLE
alignment stats error

### ISSUE THREAD

**Issue by panpandzf** [phyloacc/PhyloAcc#77]
When I used phyloacc.py to generate a snakemake job, I encountered the following error. I have about 440,000 CNE sequences. I ran the first 420,000 CNE subsets without any errors, but ran all CNEs and an error occurred when I ran to the 427,243rd CNE. I checked the bed file and confirmed that there was no problem with the position information. Any help would be greatly appreciated.
![image](https://github.com/user-attachments/assets/2a32ed00-0b6f-47ad-9dd6-2f556a57cf85)

**Comment by gwct** [comment]
Hey there @panpandzf,
Sorry I didn't reply sooner. Did you manage to figure out what was wrong? If it was a bug or something to do with the software, would you be able to post your solution so others could see it if they run into the same thing, and I could probably work on a fix.
Thanks!

**Comment by panpandzf** [comment]
Thank you very much for your reply. This is a very good software. This is not a software error, but I did not remove the CNE that does not contain all species during the concatenation process.
